server:
  port: 8080
spring:
  profiles: gateway1
  application:
    name: service-api-gateway #服务名称
  cloud:
    gateway:
      routes:
      - id: api-order
        uri: lb://service-order #http://127.0.0.1:9011 #lb://service-order
        predicates:
        - Path=/order/**
      - id: api-product
        uri: lb://service-product
        predicates:
        - Path=/product/**
        filters:
        - name: RequestRateLimiter
          args:
            key-resolver: '#{@pathKeyResolver}'  #使用SpEL从容器中获取对象(确定基于哪个维度来限流)
            redis-rate-limiter.replenishRate: 1  #令牌补充速率
            redis-rate-limiter.burstCapacity: 3  #令牌桶容量
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/ #http://127.0.0.1:9090/eureka/
      registry-fetch-interval-seconds: 5 #获取服务列表的周期：5s
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
redis:
    host: 127.0.0.1
    port: 6379
