spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stu?serverTimezone=CTT&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 101010
    driver-class-name: com.mysql.jdbc.Driver
  boot:
    admin:
      client:
            url: http://localhost:8000
mybatis:
  #basePackages: classPath:\com\tian\stu\springCloud\springbootstu\module\user\dao
  typeAliasesPackage:
  mapperLocations: classpath:mapper/*.xml

server:
    port: 8080
    servlet:
      context-path:


#management:
#    endpoints:
#             web:
#               exposure:
#                    include:  *